# Generated by Django 3.2.3 on 2021-06-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='arriendoCleta',
            fields=[
                ('idbicicleta', models.AutoField(primary_key=True, serialize=False, verbose_name='id bicicleta')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo bicicleta')),
                ('porte', models.CharField(max_length=30, verbose_name='porte bicicleta')),
                ('aro', models.IntegerField(verbose_name='aro de rueda')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
