# Generated by Django 3.2.3 on 2021-06-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_arriendocleta_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendocleta',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='marca bicicleta'),
        ),
    ]
