# Generated by Django 3.2.3 on 2021-06-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_arriendocleta_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroUsuario',
            fields=[
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre Usuario')),
                ('nombres', models.CharField(max_length=70, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=70, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('contraseña', models.CharField(max_length=30, verbose_name='Contraseña')),
            ],
        ),
    ]
